### ISSUE TITLE
Script is broken

### ISSUE THREAD

**Issue by noloader** [sormy/gentoo-vbox-builder#1] opened 2019-07-20 10:13 UTC
Attempting to use [the script](https://www.artembutusov.com/gentoo-linux-quick-installer-script) with the LiveCD and the minimal CD fails to produce a working installation. That's after trying both `USE_LIVECD_KERNEL=1` and `USE_LIVECD_KERNEL=0`.

**Comment by sormy** [comment] 2019-07-21 16:14
Seems like livecd kernel location has been changed recently from `isolinux` to `boot`. I fixed that for gist and this repo. Now it should work. Feel free to close if it works now. Please share more details what you are doing so I can reproduce the issue if you are still experiencing the issue.

**Comment by sormy** [comment] 2019-07-22 01:12
Resolving. The issue is fixed. Please reopen with details about error message if you are still experiencing the issue.

**Closed as completed by sormy** 2019-07-22 01:12 UTC
